### ISSUE TITLE
"Email when finished" - Grid_Main.vi

### ISSUE THREAD

**Issue by benlowe1** [New-Horizons-SPM/G80-nanonis-labview#6]
Dhaneesh raised the good point that his Monash email is going to be closed soon. Currently this VI sends an email notification from his email address to notify when a grid/line/cloud measurement is finished. We might need to change this.

**Comment by jhellerstedt** [comment]
Have we unburied where these are in the code?  I wouldn't be averse to just removing that feature/ I think it's possible to execute a python script from LabVIEW: could just replace it with a zulip bot message

**Comment by benlowe1** [comment]
I can't remember where exactly but I could have a dig. I agree, that would definitely be better.

**Comment by jhellerstedt** [comment]
investigated that no credentials are required to send emails using smtp.monash.edu
changed email to @benlowe1 's student email in the relevant subvi in https://github.com/New-Horizons-SPM/G80-nanonis-labview/pull/10
